on: [push, pull_request]
name: Main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: overtrue/phplint@master
        with:
          path: .
          options: --exclude=*.log
          

