on: [push, pull_request]
name: Main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: StephaneBour/actions-php-cs-fixer@1.0
      - uses: overtrue/phplint@master
        with:
          path: .
          options: --exclude=*.log
          

